spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danlmed_api
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



      #spring.jpa.hibernate.ddl-auto=update
      #spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
      #spring.datasource.username=root
      #spring.datasource.password=root
      #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      #spring.jpa.show-sql: true